kind: Deployment
apiVersion: apps/v1
metadata:
  name: kitodar
  labels:
    app: kitodar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitodar
  template:
    metadata:
      labels:
        app: kitodar
    spec:
      serviceAccountName: kitodar-service-account
      containers:
        - name: kitodar
          image: kitodar:v1
          ports:
            - containerPort: 80
---

